version: "3"
services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on: 
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes: 
      - ./:/usr/src/app:ro
    entrypoint: bash -c 'alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
    environment:
      - HOST
      - DB
      - DB_USER
      - DB_PASSWORD
      - JWT_SECRET
      - JWT_ALGORITHM
      - JWT_EXPIRY_MINUTES
      - ALLOWED_ORIGINS

volumes:
  postgres-db: