version: "3"
services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB

    volumes:
      - postgres-dev-db:/var/lib/postgresql/data
    ports: 
      - ${DB_PORT:-5432}:5432
volumes:
  postgres-dev-db: